{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-api",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.25.0.jar",
          "url": "osrsx-api-0.25.0.jar",
          "size": 4569233,
          "sha512": "c81b21325bf2578dcff0b4242671823dc53b299ecc4abd73f6e91872c0761b5e66da586db2678d353f8f07db9ff95e3793bd0a3b19e5c188b727733dab65cbe2",
          "sha256": "b1e1a2a43894dbc796229b2d4ef1b9e4a3c165e3cfd59e869fd8343b7df8273b",
          "sha1": "c08b839ac108f060d0cde0ec03fbaa258ddc49e4",
          "md5": "78399fb21c283e7f4c78ec9b95f76119"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.25.0.jar",
          "url": "osrsx-api-0.25.0.jar",
          "size": 4569233,
          "sha512": "c81b21325bf2578dcff0b4242671823dc53b299ecc4abd73f6e91872c0761b5e66da586db2678d353f8f07db9ff95e3793bd0a3b19e5c188b727733dab65cbe2",
          "sha256": "b1e1a2a43894dbc796229b2d4ef1b9e4a3c165e3cfd59e869fd8343b7df8273b",
          "sha1": "c08b839ac108f060d0cde0ec03fbaa258ddc49e4",
          "md5": "78399fb21c283e7f4c78ec9b95f76119"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-api-0.25.0-sources.jar",
          "url": "osrsx-api-0.25.0-sources.jar",
          "size": 1656457,
          "sha512": "ed7fd73ef4d286fc48ad0889c092b2a345262fc4f6e187b9f8013878861ef8e57d68c70ce2bf9dc46f70e13cfbb3c2756b6979d45c9e9358010c11d106d99001",
          "sha256": "c4de5473e49d1f15a2e33558eac40672e029289257dae26b0878db18b0047d8d",
          "sha1": "7891868d715a89bd624086b128e4bd2bd8951891",
          "md5": "daacbb310f99763f6fe2ff26cd54ab3e"
        }
      ]
    }
  ]
}
