{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-gradle",
    "version": "0.26.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.26.6.jar",
          "url": "osrsx-gradle-0.26.6.jar",
          "size": 28098,
          "sha512": "a4ccdb2f7b804f5f5987b32f8a1167bfb712610f88c66b9025696eaf5077c8e246dbf015c7c5f48d1a51636f34b1f57a5b1691ac2163af7411ef65e1f41e460c",
          "sha256": "54c16f4ed1045fa2ce953b55d601a5ab49a444df4db73ac34d057e2661c0896f",
          "sha1": "17531b6cf76a3f5f20f7dbab53fea8081c80592e",
          "md5": "930819772b6d3d2649828b8999206cc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-gradle-0.26.6.jar",
          "url": "osrsx-gradle-0.26.6.jar",
          "size": 28098,
          "sha512": "a4ccdb2f7b804f5f5987b32f8a1167bfb712610f88c66b9025696eaf5077c8e246dbf015c7c5f48d1a51636f34b1f57a5b1691ac2163af7411ef65e1f41e460c",
          "sha256": "54c16f4ed1045fa2ce953b55d601a5ab49a444df4db73ac34d057e2661c0896f",
          "sha1": "17531b6cf76a3f5f20f7dbab53fea8081c80592e",
          "md5": "930819772b6d3d2649828b8999206cc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.26.6-sources.jar",
          "url": "osrsx-gradle-0.26.6-sources.jar",
          "size": 20030,
          "sha512": "63829a8ff0eb0788b27e6847d0e1150b0e34e58bffc6638787a41e09d9f7016556e7717c27a26d9e30d5243fc5af174761b26de0ef7223f4fa34369425a3957a",
          "sha256": "73bc16d6baea13af5b8851ae36ea38e653f8063f80be6783cc1da3c22c9f9ea0",
          "sha1": "33f93e1c8f92e3fbe3e088a90627a31fc22d5f11",
          "md5": "466e36b64cd250136a5dfc5fef831075"
        }
      ]
    }
  ]
}
