{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-testkit",
    "version": "0.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.11.1.jar",
          "url": "osrsx-testkit-0.11.1.jar",
          "size": 15806,
          "sha512": "37ab4b8c323c7e6549d6fb910a98adeb0c8bdf7bc07adc9875834021cfdf3464f2ef9cbee1b1c7f7e55e7aefc6c52269bbed1f60e4cec6cfab0ccc5bc24e6f43",
          "sha256": "a2a9502e8e5192d41dd6ac63ce77ba8ffd4b9a1e3f569f632b388490bbc0b06d",
          "sha1": "feda0b3d05bfe5c0332f0cf2d7ea8bb6da900fa8",
          "md5": "f0df53df29c70f4652425dc2aef25538"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.11.1.jar",
          "url": "osrsx-testkit-0.11.1.jar",
          "size": 15806,
          "sha512": "37ab4b8c323c7e6549d6fb910a98adeb0c8bdf7bc07adc9875834021cfdf3464f2ef9cbee1b1c7f7e55e7aefc6c52269bbed1f60e4cec6cfab0ccc5bc24e6f43",
          "sha256": "a2a9502e8e5192d41dd6ac63ce77ba8ffd4b9a1e3f569f632b388490bbc0b06d",
          "sha1": "feda0b3d05bfe5c0332f0cf2d7ea8bb6da900fa8",
          "md5": "f0df53df29c70f4652425dc2aef25538"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-testkit-0.11.1-sources.jar",
          "url": "osrsx-testkit-0.11.1-sources.jar",
          "size": 2356,
          "sha512": "27fd8c4cd69e95c16aeef3cc1d9cdcad60e5529445ef511dc9b2772d00063f0e73822f9fabe0b0a7642b820f0d0d568f0eac5e962d4c5dc2cc20202b50927c5b",
          "sha256": "a6cdfcdee467d5649daf8cb35091d3947e2ccf8a31e73233a5fff082099dd701",
          "sha1": "4573cfa4deda74541480523078a4ee175ca4ce7f",
          "md5": "fff035363a634508275ae061c28018ab"
        }
      ]
    }
  ]
}
