{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-testkit",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.1.5.jar",
          "url": "osrsx-testkit-0.1.5.jar",
          "size": 14202,
          "sha512": "4858d8993042e8d8d247626063264024186fcfb153e5d46a56d657f3a52b68956acfadb7788659eaa2cdb6a0b243cf896573b2a1bed69997f0dfab3fca2f29fe",
          "sha256": "d4bede5355d4032ae41266a2d8e76fb3f10af3fc1414fbee9ab81cd9b959d8ae",
          "sha1": "e0d408c4bff291b27d9c65605e9d3739247406c1",
          "md5": "2dfa9f2d064de5ad099ff9bd9449d67a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.1.5.jar",
          "url": "osrsx-testkit-0.1.5.jar",
          "size": 14202,
          "sha512": "4858d8993042e8d8d247626063264024186fcfb153e5d46a56d657f3a52b68956acfadb7788659eaa2cdb6a0b243cf896573b2a1bed69997f0dfab3fca2f29fe",
          "sha256": "d4bede5355d4032ae41266a2d8e76fb3f10af3fc1414fbee9ab81cd9b959d8ae",
          "sha1": "e0d408c4bff291b27d9c65605e9d3739247406c1",
          "md5": "2dfa9f2d064de5ad099ff9bd9449d67a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-testkit-0.1.5-sources.jar",
          "url": "osrsx-testkit-0.1.5-sources.jar",
          "size": 2257,
          "sha512": "d11fe526da06968c38550269405d0c655b3ea5de21e01edff0e669a57d43e5655d672bb86417aa2774eb31dec14a39fd5fb0c18ef51b92cb73045bcae905340a",
          "sha256": "5fe6fed5fe7292edb956feb743c611f08fce1e700ca55f1765d4f416319dabec",
          "sha1": "7b415d5b072641d2588ff9ea3ba5a85d45cf1457",
          "md5": "ae8489a43f07ebaf9b15686c3a47feaf"
        }
      ]
    }
  ]
}
