{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-testkit",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.1.0.jar",
          "url": "osrsx-testkit-0.1.0.jar",
          "size": 14202,
          "sha512": "1dfbe1ebf2b0a86a0b71e07eb1c2c3efa54e257c7b9704ad97ff6aef9f3a4cde78ae09a6228826c4620037d2c96924074c296b91489f694e89d7d35f23d15ddc",
          "sha256": "818858269aa3295cfb2ca35500ef7679780f418104b9087dd1cc3f5d1f1fd981",
          "sha1": "5228673f97a5462cfd6e9449658cc2818f4c02ea",
          "md5": "d558be885c2e98a470e280da632f37dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.1.0.jar",
          "url": "osrsx-testkit-0.1.0.jar",
          "size": 14202,
          "sha512": "1dfbe1ebf2b0a86a0b71e07eb1c2c3efa54e257c7b9704ad97ff6aef9f3a4cde78ae09a6228826c4620037d2c96924074c296b91489f694e89d7d35f23d15ddc",
          "sha256": "818858269aa3295cfb2ca35500ef7679780f418104b9087dd1cc3f5d1f1fd981",
          "sha1": "5228673f97a5462cfd6e9449658cc2818f4c02ea",
          "md5": "d558be885c2e98a470e280da632f37dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-testkit-0.1.0-sources.jar",
          "url": "osrsx-testkit-0.1.0-sources.jar",
          "size": 2257,
          "sha512": "2085989e9a43540f6b34cb1fc7e1693c9538e486bfe44287498bd91729ef4808ed03e466348235d094700b539fd8803e0426fe24e5ede43b84318e4500230cab",
          "sha256": "e4ae4b048e403762474b66b02f5396d42774b0ef56ac0b5ce15355028af23906",
          "sha1": "04aa18ff54e7cd21a163d81c33f85b4bc31164a8",
          "md5": "ca99cd6eb36e1c834beb38e90e4130f6"
        }
      ]
    }
  ]
}
