{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-testkit",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.11.0.jar",
          "url": "osrsx-testkit-0.11.0.jar",
          "size": 15495,
          "sha512": "5a031e3d9f97d666ad1c6086760c4bb5598305609db215d6b2c3a2d9886e4a79e3b62543f28ff26a7209f564617234d9fc4a65c497ff634b2931ac6fbedfd75a",
          "sha256": "ffb32144e426204e3e75e0c72ef0d832411a6a37a35a8146dc212879e4088315",
          "sha1": "a6c0dbc10bac10acbb6dab0a15a727f772388962",
          "md5": "d2c72fe4b12f83c0bca48b9617a6ab67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.11.0.jar",
          "url": "osrsx-testkit-0.11.0.jar",
          "size": 15495,
          "sha512": "5a031e3d9f97d666ad1c6086760c4bb5598305609db215d6b2c3a2d9886e4a79e3b62543f28ff26a7209f564617234d9fc4a65c497ff634b2931ac6fbedfd75a",
          "sha256": "ffb32144e426204e3e75e0c72ef0d832411a6a37a35a8146dc212879e4088315",
          "sha1": "a6c0dbc10bac10acbb6dab0a15a727f772388962",
          "md5": "d2c72fe4b12f83c0bca48b9617a6ab67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-testkit-0.11.0-sources.jar",
          "url": "osrsx-testkit-0.11.0-sources.jar",
          "size": 2337,
          "sha512": "c519483db85e3d6bc3ac033ca3b96c7fb897451752c01fed1650e38119cc202e706082f01937bd692c0bb7c9432a732b0a5b0fe6e7c8ce23aee18f4e64fe2948",
          "sha256": "5cd6ab2097c26861a68c29683ccc7f877a7870cd97ed3d3a683264db23ae5819",
          "sha1": "935ad9d3597598a830ea4761647c234e529dce9a",
          "md5": "7e67ee5c0cc4a6f61c21c6b5de228c70"
        }
      ]
    }
  ]
}
