{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-api",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.25.6.jar",
          "url": "osrsx-api-0.25.6.jar",
          "size": 3478439,
          "sha512": "d983e9cce5e08e97e20f99025ca11a24fadc354ad2004bec9cd2576c25375efc8e58ac9d6b97ef0099ceac84930824d2a99f1ce8cadc1297b4b42cadd02b4dd6",
          "sha256": "1382e6423b3dc1551d78680de124676686a875803d12adc6e334da9618c778e4",
          "sha1": "dbabbae84a194c5fafc4e0515ed057e0d9834e19",
          "md5": "bf0c837d2d42d73bc8d6397f3d1e7684"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.25.6.jar",
          "url": "osrsx-api-0.25.6.jar",
          "size": 3478439,
          "sha512": "d983e9cce5e08e97e20f99025ca11a24fadc354ad2004bec9cd2576c25375efc8e58ac9d6b97ef0099ceac84930824d2a99f1ce8cadc1297b4b42cadd02b4dd6",
          "sha256": "1382e6423b3dc1551d78680de124676686a875803d12adc6e334da9618c778e4",
          "sha1": "dbabbae84a194c5fafc4e0515ed057e0d9834e19",
          "md5": "bf0c837d2d42d73bc8d6397f3d1e7684"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-api-0.25.6-sources.jar",
          "url": "osrsx-api-0.25.6-sources.jar",
          "size": 1717544,
          "sha512": "3995878260ac17c81b4feff3ad714cedc2db310c0c703318d72a834af959d3743ce62bada2a585fec2fe00cae2c18c223880218c2c8edb2a9797b52574dde941",
          "sha256": "9123be013904e278fa26ed17fac93d970e17461642d17deef1434863673377ba",
          "sha1": "ea3a5b10aca2ea20b99b9aefdc5da3d875fef282",
          "md5": "a06e1c4e468fd079ef0035fd80b3ef79"
        }
      ]
    }
  ]
}
