{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-gradle",
    "version": "0.27.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.27.1.jar",
          "url": "osrsx-gradle-0.27.1.jar",
          "size": 28098,
          "sha512": "76e3195c5298bba64b501f791126dba7e41bf56495146d2ed44beec249e2cf057584d6d27aafc5113745897a9aaee4699c158dc6eab80638f8b6ff768cf5d34f",
          "sha256": "e5c283ed08c758f023343e5053c1e1aa43548c3316e40d5cb8d514e173fab872",
          "sha1": "cbb27df59088f876f1068b397f1a78454aae574c",
          "md5": "fdf93cfbfd58a2f9809b0d989f629157"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-gradle-0.27.1.jar",
          "url": "osrsx-gradle-0.27.1.jar",
          "size": 28098,
          "sha512": "76e3195c5298bba64b501f791126dba7e41bf56495146d2ed44beec249e2cf057584d6d27aafc5113745897a9aaee4699c158dc6eab80638f8b6ff768cf5d34f",
          "sha256": "e5c283ed08c758f023343e5053c1e1aa43548c3316e40d5cb8d514e173fab872",
          "sha1": "cbb27df59088f876f1068b397f1a78454aae574c",
          "md5": "fdf93cfbfd58a2f9809b0d989f629157"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.27.1-sources.jar",
          "url": "osrsx-gradle-0.27.1-sources.jar",
          "size": 20030,
          "sha512": "a5866a3bd348bc9ba35091874bfcf06d801fc6706a5139e27e99abdddf0ba7bf9061c581a0bb659ca1d790fe79a104d366e4e1f60961b2fd6001c21d47a9e48e",
          "sha256": "a183dc3a77d1072db05be05017f86f2a98e62f132f42cb73021b9fd056201977",
          "sha1": "95f6e55b4e59acdb4e356d30a9e76774f4f51831",
          "md5": "98a75e0d3d484cd63255823c5e171fe9"
        }
      ]
    }
  ]
}
