{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-gradle",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.1.3.jar",
          "url": "osrsx-gradle-0.1.3.jar",
          "size": 21365,
          "sha512": "167e9dda1b41fcd4f1a4b69acec0ee683201f0608ac4dd9aee0ca0ad5c8df3b5e80948ef17baadf2b0f777961a3650592fefab7b854a6de2267fc5059ea21074",
          "sha256": "4e772a55c867fbfdf248226db3fe46726b2090140a84fda12eba759067769227",
          "sha1": "854eeaad38240ec0c9057e728c11b214e8b73da8",
          "md5": "f6aff93db5e3a962910e4c84e8297828"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-gradle-0.1.3.jar",
          "url": "osrsx-gradle-0.1.3.jar",
          "size": 21365,
          "sha512": "167e9dda1b41fcd4f1a4b69acec0ee683201f0608ac4dd9aee0ca0ad5c8df3b5e80948ef17baadf2b0f777961a3650592fefab7b854a6de2267fc5059ea21074",
          "sha256": "4e772a55c867fbfdf248226db3fe46726b2090140a84fda12eba759067769227",
          "sha1": "854eeaad38240ec0c9057e728c11b214e8b73da8",
          "md5": "f6aff93db5e3a962910e4c84e8297828"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.1.3-sources.jar",
          "url": "osrsx-gradle-0.1.3-sources.jar",
          "size": 12758,
          "sha512": "e2e5b7762698214694f1f6312d9b91ec183078e5752678681ef2d6209165719b39d24f03dbd42714812d6739404be03d4d5cd4cd91847398d0d21301916dc0b1",
          "sha256": "d2c1b7d1845565c5dd7d8b1a3a9b8cf863da03410e46eef4811588bb3fa962b4",
          "sha1": "dc174b20aa8cb45133e6abd609d79868c1ee3c41",
          "md5": "0afb513d3e71832f5fab26dced0d308d"
        }
      ]
    }
  ]
}
