{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-gradle",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.1.1.jar",
          "url": "osrsx-gradle-0.1.1.jar",
          "size": 21150,
          "sha512": "d0dc129a1a937808cd15046613f55cc06f1db5666348114325ad293ca4200c6cf687245175bf905637c6e422b104e5467be2c09fc2c3e146831a8e489552916b",
          "sha256": "ef017da8d0b3c7693a56f897e0c9a697e1fa2db9ec064cebb2dfbe9f068dc04d",
          "sha1": "16f556078dc6197a5f78429c39234af7570e408a",
          "md5": "47a5ce01b2c6be24090b2b8e7de1cf41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-gradle-0.1.1.jar",
          "url": "osrsx-gradle-0.1.1.jar",
          "size": 21150,
          "sha512": "d0dc129a1a937808cd15046613f55cc06f1db5666348114325ad293ca4200c6cf687245175bf905637c6e422b104e5467be2c09fc2c3e146831a8e489552916b",
          "sha256": "ef017da8d0b3c7693a56f897e0c9a697e1fa2db9ec064cebb2dfbe9f068dc04d",
          "sha1": "16f556078dc6197a5f78429c39234af7570e408a",
          "md5": "47a5ce01b2c6be24090b2b8e7de1cf41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.1.1-sources.jar",
          "url": "osrsx-gradle-0.1.1-sources.jar",
          "size": 12431,
          "sha512": "a683d330b7c4ab732e7d38e8eb2de6abb2d82a436c861c9e8fa1aef87ceb6a919ffc78e44e5e2ca42d127f33008238039d3f72ced29b992855284645fb4446ec",
          "sha256": "5184c8bef7b6964c047433ae87d4d1a75c0cb682b0013eb546fe1fdb8e7a389a",
          "sha1": "3845280e7a8aafb9b9d41d97b374cd0bd8fee205",
          "md5": "79332ce3b1253e6a71276f03e78a1cce"
        }
      ]
    }
  ]
}
