{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-api",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.1.3.jar",
          "url": "osrsx-api-0.1.3.jar",
          "size": 245907,
          "sha512": "cf704806310199abca79551e2a19a3d17145475932c880036281999a6d3be54b081b1819c2269d7756bc1fbcb7626740cf510407c15e2a603d6f18a11173833d",
          "sha256": "c2a768db718f6d16c8c84eee864a451af819edab9501569f629fcaa2e75a8e2a",
          "sha1": "c1edae62f806414898b3829db5c86e6991e23deb",
          "md5": "6352448c565dca8cc69b89e19832ab93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.1.3.jar",
          "url": "osrsx-api-0.1.3.jar",
          "size": 245907,
          "sha512": "cf704806310199abca79551e2a19a3d17145475932c880036281999a6d3be54b081b1819c2269d7756bc1fbcb7626740cf510407c15e2a603d6f18a11173833d",
          "sha256": "c2a768db718f6d16c8c84eee864a451af819edab9501569f629fcaa2e75a8e2a",
          "sha1": "c1edae62f806414898b3829db5c86e6991e23deb",
          "md5": "6352448c565dca8cc69b89e19832ab93"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-api-0.1.3-sources.jar",
          "url": "osrsx-api-0.1.3-sources.jar",
          "size": 80195,
          "sha512": "2b24637bcf4c7d17e4afccbbbc4beeb0319a386ebdb03054aeaa0beea48329380a543830b8a9706578a3b1c3fa3e67d21cf3eec6c015ccaadb85c441a968392f",
          "sha256": "d17acd06e0a27d2f336a122972843e9559d2597f0b87fdd9b5cb36cdfaacbff7",
          "sha1": "78a0ffb302ff8095b3799cd618d974c00dd3a0ca",
          "md5": "cf24cccfcf8905095658202c5b899102"
        }
      ]
    }
  ]
}
