{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-api",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.1.7.jar",
          "url": "osrsx-api-0.1.7.jar",
          "size": 249816,
          "sha512": "17f6577e01e581b46ecd60012ed269fd31134644ec991400a2b8b2a2ff966096d09124b040633be605a71f3661d7f6af77f31084d85e4898aacea6afead004a2",
          "sha256": "dcc2d1276f52ec66cff65ad4df4a1dde387181c6ed40c2ece1c825c8c6edc789",
          "sha1": "9706711061e1b8b06a63788245e2cad978f7d011",
          "md5": "33067ed5642bd6e1e3444321aa9c10ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.1.7.jar",
          "url": "osrsx-api-0.1.7.jar",
          "size": 249816,
          "sha512": "17f6577e01e581b46ecd60012ed269fd31134644ec991400a2b8b2a2ff966096d09124b040633be605a71f3661d7f6af77f31084d85e4898aacea6afead004a2",
          "sha256": "dcc2d1276f52ec66cff65ad4df4a1dde387181c6ed40c2ece1c825c8c6edc789",
          "sha1": "9706711061e1b8b06a63788245e2cad978f7d011",
          "md5": "33067ed5642bd6e1e3444321aa9c10ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-api-0.1.7-sources.jar",
          "url": "osrsx-api-0.1.7-sources.jar",
          "size": 83432,
          "sha512": "3b1cdf53e538340b06d5e7461c780a52b46980d206176d9dee70230b0e8b85be4e1367a1076b1e790fa13decbf7531a940a083d0caa3fe320becda22c5f58087",
          "sha256": "ecdbb0164cfb501890797790d397722b794e19186852897545ece85ec96ffac6",
          "sha1": "89b5832095f90f1e330b532f72f8c7404ed7df09",
          "md5": "fbcdaa3951a94330034c1577e60b4886"
        }
      ]
    }
  ]
}
