{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-gradle",
    "version": "0.11.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.11.5.jar",
          "url": "osrsx-gradle-0.11.5.jar",
          "size": 26324,
          "sha512": "313b1df2bdd337881addffca61077de3a37627383c0eff78bc84d40c835c288e081c1cbaee56177060c976d8d620278f65d7343df29c7941253560b611a82192",
          "sha256": "3e9eb1817dbf20496a827cdf1b649d192213e417ca9ca2c4afffe34b2da12e8b",
          "sha1": "63f89f65b6d33f17244a388408efb46d8dcd63c4",
          "md5": "6bf56381b014ec77e4f925bc45f7ef58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-gradle-0.11.5.jar",
          "url": "osrsx-gradle-0.11.5.jar",
          "size": 26324,
          "sha512": "313b1df2bdd337881addffca61077de3a37627383c0eff78bc84d40c835c288e081c1cbaee56177060c976d8d620278f65d7343df29c7941253560b611a82192",
          "sha256": "3e9eb1817dbf20496a827cdf1b649d192213e417ca9ca2c4afffe34b2da12e8b",
          "sha1": "63f89f65b6d33f17244a388408efb46d8dcd63c4",
          "md5": "6bf56381b014ec77e4f925bc45f7ef58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-gradle-0.11.5-sources.jar",
          "url": "osrsx-gradle-0.11.5-sources.jar",
          "size": 17689,
          "sha512": "46abc4f26f2f02a32790e7d1a1f5ac204d076e60246faac33cedee6e9ef3e0f3446caee37e531080bff82999411a2f83211fec2f736c6f58bd8eb6af29267121",
          "sha256": "170bb01fbe689b8c404a41e3f4ac6089fb9602ba6050a8302c2d3780fab91c15",
          "sha1": "d3048678b70b63deb9fffdf8c2f1d15861b52804",
          "md5": "a4e2e5836a5c7336c6c32e45a7f8993b"
        }
      ]
    }
  ]
}
