{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-testkit",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.1.3.jar",
          "url": "osrsx-testkit-0.1.3.jar",
          "size": 14202,
          "sha512": "75fa1313d4209db66f17462faf3f19c545d36f0217a5ecc74559a41390dba13adf3afa3d873916332af2aee813e9a29b1f4267c7eff318b2a3f7b1d26bc8f98d",
          "sha256": "3e6b82d2758027d2f3b1a751df05e5b7d524cf6d666d4022f4f4a825bb21e442",
          "sha1": "8a02527ff815d208fcb1436e18d084a509ba14ad",
          "md5": "0d21461aef984309d0f40078f7832ec1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.1.3.jar",
          "url": "osrsx-testkit-0.1.3.jar",
          "size": 14202,
          "sha512": "75fa1313d4209db66f17462faf3f19c545d36f0217a5ecc74559a41390dba13adf3afa3d873916332af2aee813e9a29b1f4267c7eff318b2a3f7b1d26bc8f98d",
          "sha256": "3e6b82d2758027d2f3b1a751df05e5b7d524cf6d666d4022f4f4a825bb21e442",
          "sha1": "8a02527ff815d208fcb1436e18d084a509ba14ad",
          "md5": "0d21461aef984309d0f40078f7832ec1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-testkit-0.1.3-sources.jar",
          "url": "osrsx-testkit-0.1.3-sources.jar",
          "size": 2257,
          "sha512": "244623bd4f6e84d1857bdb59c571d311ce01aaa7144bdf6ead775004caef798654dcff5579d9cf5d085d60d6fcfa377fddeb48e4ccf58eb428e6cfa7b3c293ec",
          "sha256": "fc8c6226795d75fb45f44617f055940274cb7f9721fffb2a94f647d792dcc428",
          "sha1": "7b9af3ea4c6ced2d88ef2443644cd5af2d62ac5b",
          "md5": "7a6403716f80dd9d4584798377174134"
        }
      ]
    }
  ]
}
