{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-api",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.1.1.jar",
          "url": "osrsx-api-0.1.1.jar",
          "size": 245906,
          "sha512": "ca330e8ca8c1b588bd7a2e01a51be7b85c3086f25f619057d630556fe45043ef9f54f5e127e6514ff7226d93cf3b05903d9c23091cac84bef784aad95ebfb7bb",
          "sha256": "90ad7a4f3e2e3835cbbfc8e3cad9406acf50980b0729ca1e226d2c232534a1bd",
          "sha1": "8e2d3cff8beac7c95899a4f86b8701fb04bffd8b",
          "md5": "59b52af777ace2c6d19cd78ea86ec4dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.1.1.jar",
          "url": "osrsx-api-0.1.1.jar",
          "size": 245906,
          "sha512": "ca330e8ca8c1b588bd7a2e01a51be7b85c3086f25f619057d630556fe45043ef9f54f5e127e6514ff7226d93cf3b05903d9c23091cac84bef784aad95ebfb7bb",
          "sha256": "90ad7a4f3e2e3835cbbfc8e3cad9406acf50980b0729ca1e226d2c232534a1bd",
          "sha1": "8e2d3cff8beac7c95899a4f86b8701fb04bffd8b",
          "md5": "59b52af777ace2c6d19cd78ea86ec4dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-api-0.1.1-sources.jar",
          "url": "osrsx-api-0.1.1-sources.jar",
          "size": 80195,
          "sha512": "77d31bc7278e06741161886d9729190dcd7e80cfbc1ebbd60cf6b995e0a9ea8f4a0c103e81ac84ebb444a4535914ca6948a3ac4ec93bf6c3bd37a819916ac365",
          "sha256": "fd8fbee18612570e99e1009116729ba9699049903ead9f68746fe6d5b8a68fd1",
          "sha1": "4e14cd185f0ef215d554f38ddb5c9b4ff05f6f17",
          "md5": "090098d87d4452224dbce66a3f6de7f8"
        }
      ]
    }
  ]
}
