{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-testkit",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.1.1.jar",
          "url": "osrsx-testkit-0.1.1.jar",
          "size": 14202,
          "sha512": "0fd315254a50b47cd2baf4046a190541c6958b8f9201bd1e205bf7dbd0ccfa2b95aacf9038ed0373c19421e4703c9c01656009eb85156a73fec80cc9ec89295b",
          "sha256": "fe9249433c4b67e0037c67a8c0bb89cdcba8b2a56c9bce6e8f445d3a4e116434",
          "sha1": "377c9005ebb166bd9781a821c052519b2623bba1",
          "md5": "44b6512f3d5b82dc36b905f0efc968b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.1.1.jar",
          "url": "osrsx-testkit-0.1.1.jar",
          "size": 14202,
          "sha512": "0fd315254a50b47cd2baf4046a190541c6958b8f9201bd1e205bf7dbd0ccfa2b95aacf9038ed0373c19421e4703c9c01656009eb85156a73fec80cc9ec89295b",
          "sha256": "fe9249433c4b67e0037c67a8c0bb89cdcba8b2a56c9bce6e8f445d3a4e116434",
          "sha1": "377c9005ebb166bd9781a821c052519b2623bba1",
          "md5": "44b6512f3d5b82dc36b905f0efc968b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-testkit-0.1.1-sources.jar",
          "url": "osrsx-testkit-0.1.1-sources.jar",
          "size": 2257,
          "sha512": "42f94d5f45979ad1c576f4b40eb7e5fa05d374346118fbf9b65a68efea69e349da97dff7170ede053627a319510c4177525d18ee2d484539b7bed15d2dff6f6f",
          "sha256": "59d626f9364946920b30b259be0aa1610da237daa0a7f60ccb7cf3f591c30092",
          "sha1": "b7c4f2d68671496ecb8ddff69333f05f8f84b1ee",
          "md5": "67ca191685c9f0d0bb10ed448a11f994"
        }
      ]
    }
  ]
}
