{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-testkit",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.4.0.jar",
          "url": "osrsx-testkit-0.4.0.jar",
          "size": 15174,
          "sha512": "01c78783a75d3a3df530cce33449c43bcf9276cfaf951aaffabe7c9cda3b9c82293a552b5c07194b8901822e29a5c6b1cb0c02b0884de4729eaa6ea687b2f9c4",
          "sha256": "acf5e86f6f56410fdf9b9b04fb0042880c3cf5e3909794bfb19ac47988d0472e",
          "sha1": "6ed5011e820bb277f30234c3b53b800c195cab6d",
          "md5": "6d54eddba8f4c3bac75dde482ed6bfbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.osrsx",
          "module": "osrsx-api",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.mockito.kotlin",
          "module": "mockito-kotlin",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-testkit-0.4.0.jar",
          "url": "osrsx-testkit-0.4.0.jar",
          "size": 15174,
          "sha512": "01c78783a75d3a3df530cce33449c43bcf9276cfaf951aaffabe7c9cda3b9c82293a552b5c07194b8901822e29a5c6b1cb0c02b0884de4729eaa6ea687b2f9c4",
          "sha256": "acf5e86f6f56410fdf9b9b04fb0042880c3cf5e3909794bfb19ac47988d0472e",
          "sha1": "6ed5011e820bb277f30234c3b53b800c195cab6d",
          "md5": "6d54eddba8f4c3bac75dde482ed6bfbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-testkit-0.4.0-sources.jar",
          "url": "osrsx-testkit-0.4.0-sources.jar",
          "size": 2318,
          "sha512": "cfcd75d06080106ab97c74aacda8f7b6c1c32a5a3e6224285d95bef198e79175b1ab46ac49ea20cc6f575923d8f0d3a6a51c9d63d3d632a6c9a8cf0a5e81dbb3",
          "sha256": "52d7e3c79d6a05716059ef8ae34cb3455a6c5fdd1d60298fbd28f9082ca96299",
          "sha1": "a40d90560d10ddd4db7e856f686e16b02441cd40",
          "md5": "ed9fc9819c2a77acbc2775ae41960994"
        }
      ]
    }
  ]
}
