{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-api",
    "version": "0.27.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.27.1.jar",
          "url": "osrsx-api-0.27.1.jar",
          "size": 3492327,
          "sha512": "e938e6cb9993a40b19bc36edbd65750cfe3115e2056b6917718ecef3a43f0755e66f9c4cd3308812462da92fd0ea41f65f2be8830c09491f94f571e1ff158790",
          "sha256": "758d50f88a5ae2578f066543aeb6d6886c36ac9af17f20ee5c864b84cd339716",
          "sha1": "821888a858743ec956aa56a38d3bcae5be7d0e10",
          "md5": "30216ad8eaf822df85cd7216491fa75b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.27.1.jar",
          "url": "osrsx-api-0.27.1.jar",
          "size": 3492327,
          "sha512": "e938e6cb9993a40b19bc36edbd65750cfe3115e2056b6917718ecef3a43f0755e66f9c4cd3308812462da92fd0ea41f65f2be8830c09491f94f571e1ff158790",
          "sha256": "758d50f88a5ae2578f066543aeb6d6886c36ac9af17f20ee5c864b84cd339716",
          "sha1": "821888a858743ec956aa56a38d3bcae5be7d0e10",
          "md5": "30216ad8eaf822df85cd7216491fa75b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-api-0.27.1-sources.jar",
          "url": "osrsx-api-0.27.1-sources.jar",
          "size": 1723356,
          "sha512": "917a29610dbd15de56233bf761f45d332259e08a4aa68734ee567d1ab11821fc4fc5fb39be3e0b6728ca2270c6958f2d83642243e6d5b3340a160b7d3de55c73",
          "sha256": "b50ba36b7a9d4ac0af43ab8265d5f686ee382ed9377ac541bbd2397dbe49aa51",
          "sha1": "7e1b2f7fea3e2548125ef8216fe622fc5505808c",
          "md5": "769f409910ff710d37009f73a05b8d3b"
        }
      ]
    }
  ]
}
