{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-api",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.17.0.jar",
          "url": "osrsx-api-0.17.0.jar",
          "size": 4338365,
          "sha512": "a4e69566038494ef0b76341764a5d9d0d60807d47b16fd9686326b2b4e1305e55587f7b40ebeb8b8228a069db27099ed3db2d657ed8c15059b1930856629f349",
          "sha256": "d3d366ce43ed00a74e3389e5dc5f83d9d08b19146cae7e1252bae0c02bbc3f55",
          "sha1": "c0c699b4a62677de583f91f8ca0ce58210ebf51f",
          "md5": "578734e02dbb7a070edd0ad17eaa884f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.17.0.jar",
          "url": "osrsx-api-0.17.0.jar",
          "size": 4338365,
          "sha512": "a4e69566038494ef0b76341764a5d9d0d60807d47b16fd9686326b2b4e1305e55587f7b40ebeb8b8228a069db27099ed3db2d657ed8c15059b1930856629f349",
          "sha256": "d3d366ce43ed00a74e3389e5dc5f83d9d08b19146cae7e1252bae0c02bbc3f55",
          "sha1": "c0c699b4a62677de583f91f8ca0ce58210ebf51f",
          "md5": "578734e02dbb7a070edd0ad17eaa884f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-api-0.17.0-sources.jar",
          "url": "osrsx-api-0.17.0-sources.jar",
          "size": 1592583,
          "sha512": "1149ac092711fc14ad7a7f239885468c6a18ecbe4f0047f5aec50c1331cd37e3a32cef5e900b57de4ce5d72bbf5b470c3f9820c09f5639a0e69b2846b99ae17f",
          "sha256": "b7b4b8fb08b3e2a0604f4e805b0a08c830dccfc8e7ab1ffe6c5eb8a965e26761",
          "sha1": "5171cf3c34c2ad5b2221998d0d792104580ee87e",
          "md5": "2baf92750c834aa48db790cc7b8ac2dc"
        }
      ]
    }
  ]
}
