{
  "formatVersion": "1.1",
  "component": {
    "group": "io.osrsx",
    "module": "osrsx-api",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.9.0.jar",
          "url": "osrsx-api-0.9.0.jar",
          "size": 446370,
          "sha512": "79c08ee4655ac5f5097e519f07113be12a5f4c1212659d7607f777e87d804ef9d4b229c4eed041b6782919c798a1529ebb6c58156c91d2ab64a8730e48e07582",
          "sha256": "3a6b5e131d664c86190a4856532198d48c3bdd0c6cc24ca002d1d2ccbf87de43",
          "sha1": "bc6c131990a637c3bf5ff9bd1ed52db35fffa527",
          "md5": "04d24b0ba734cf4b466724363fb96379"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrsx-api-0.9.0.jar",
          "url": "osrsx-api-0.9.0.jar",
          "size": 446370,
          "sha512": "79c08ee4655ac5f5097e519f07113be12a5f4c1212659d7607f777e87d804ef9d4b229c4eed041b6782919c798a1529ebb6c58156c91d2ab64a8730e48e07582",
          "sha256": "3a6b5e131d664c86190a4856532198d48c3bdd0c6cc24ca002d1d2ccbf87de43",
          "sha1": "bc6c131990a637c3bf5ff9bd1ed52db35fffa527",
          "md5": "04d24b0ba734cf4b466724363fb96379"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "osrsx-api-0.9.0-sources.jar",
          "url": "osrsx-api-0.9.0-sources.jar",
          "size": 128344,
          "sha512": "4757339d8b18c92a01036d275e1769c0bee084d41c2ca91daf60d8c8fff89a0364201e022a7a0dd45043779cc5df49b2b17ddaf47aaad334709d861fbc97b9c9",
          "sha256": "9b350b1b9383ccd9e6585fbfd27e3f5394724b45a7d2b7232bc4a958de094966",
          "sha1": "5d2dc45492db78d7b665250fb1510a917779434f",
          "md5": "4a1a932d4616db2a641579725f656d90"
        }
      ]
    }
  ]
}
